### ISSUE TITLE
There was a problem connecting to SprinklerD. - Error: connect ECONNREFUSED ::1:80

### ISSUE THREAD

**Issue by woodgieboodgie** [sfeakes/homebridge-sprinklerd#8]
upgraded to HB1.6 and NodeJS v18.16.0 and now receiving the error in the log:

There was a problem connecting to SprinklerD. - Error: connect ECONNREFUSED ::1:80

What did i break?  Sprinklerd v.0.1.1 installed.

**Comment by sfeakes** [comment]
I just installed those versions HB 1.6.1 & NodeJV c18.16.0 and all works, so it's not that.

Error: connect ECONNREFUSED means that is can't connect to the machine running SprinklerD, so I would check the config for the homebridge-sprinklerd plugin.   The `server` part is what you are after.    My guess is if you are using a hostname, that name is not being resolved on your network for some reason. If you are using an IP address, check SprinklerD is up and running on that IP address.  Also check the `port` setting under `server`, to make sure that's accurate.

**Comment by woodgieboodgie** [comment]
Server is set as 'localhost' and has operated on that setting for ages. I can open the browser and see the sprinklers despite receiving this error.. which is odd.
port is 80.

**Comment by sfeakes** [comment]
if you are using localhost (ie sprinklerd and homebridge on same machine) that is very odd you are getting that error.  The error is thrown from the node library for requesting URLs.

I just installed sprinklerd on the same machine as homebridge, and I see the problem.  Anything that resolves back to 127.0.0.1 the local loop back interface fails.  So using localhost or 127.0.0.1 will fail.   Anything that resolved to external ip seems to work.  So you can either the external IP address, the actual hostname of the pi or 127.0.1.1

This is an issue with Node 18.16.0 (or a dependency library).  I'll see if I can find a workaround.  In the meantime, look in your `/etc/hosts` file, the local machine name will be listed under 127.0.1.1, I suggest you use that rather than localhost.

**Comment by sfeakes** [comment]
It was a change made in Node.JS that forced ipv6 resolution before ipv4.  I've updated homebridge-sprinklerd to overcome this.  If you update to v0.1.2 it should be fixed.

**Comment by woodgieboodgie** [comment]
That fixed it.  Thank you.
